spring.application.name=assessment-app
spring.datasource.url=jdbc:postgresql://localhost:5432/assessment
spring.datasource.username=postgres
spring.datasource.password=@dm1n123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true